Repository eggplants/wbsv-cli, pull requests merged in 2020-05, with the labels that each got.

#28 Import argparse
  .gitignore
  .vscode/settings.json
  README.md
  setup.py
  wbsv/Archive.py
  wbsv/Help.py
  wbsv/Interact.py
  wbsv/ParseArgs.py
  wbsv/Version.py
  wbsv/__init__.py
  wbsv/main.py
Labels: maintainability

#42 Add error handling and anable to print errtype
  wbsv/Archive.py
  wbsv/Find.py
Labels: bug

#45 Object oriented programing
  wbsv/ParseArgs.py
  wbsv/archiver.py
  wbsv/finder.py
  wbsv/interactive.py
  wbsv/main-refactor.py
Labels: enhancement, maintainability
